# 自定义层

构造一个没有任何参数的自定义层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到构建更复杂的模型中

In [4]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())
Y = net(torch.rand(4,8))
Y.mean()

tensor(-9.3132e-09, grad_fn=<MeanBackward0>)

带参数的图层

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.8819,  0.0333,  0.8758],
        [-0.1279,  0.9386,  0.1734],
        [-0.8121, -0.7969,  1.4854],
        [ 0.4425,  2.5460,  0.2351],
        [-0.0833, -1.0223,  1.0289]], requires_grad=True)

使用自定义层直接直行正向传播计算

In [7]:
linear(torch.rand(2, 5))

tensor([[0.0000e+00, 4.4115e-03, 4.5953e+00],
        [0.0000e+00, 0.0000e+00, 4.5231e+00]])

使用自定义层构建模型,像使用内置的全连接层一样使用自定义层

In [10]:
net = nn.Sequential(MyLinear(64, 8),MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[1.4491],
        [0.0000]])